[features]
seeds = false
skip-lint = false
[programs.localnet]
guessing_game = "HmFWY4iTD1Hd5yP3q129fr8RC3ZwJeAVqvBKWM6d17zZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
